# Generated by Django 4.2.2 on 2023-07-12 04:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageApp',
            fields=[
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_id', models.IntegerField(error_messages={'unique': 'This vehicle has already been registered.'}, primary_key=True, serialize=False)),
                ('vehicle_owner_id', models.IntegerField()),
                ('vehicle_uuid', models.CharField(max_length=100)),
                ('vehicle_pub_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SharedVehicleData',
            fields=[
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shared_vehicle_data', serialize=False, to='garageApp.garageapp')),
                ('is_occupied', models.BooleanField()),
                ('sharing_enabled', models.BooleanField()),
                ('is_request_pending', models.BooleanField()),
                ('max_assist_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SharedVehicleOwnerData',
            fields=[
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='shared_vehicle_owner_data', serialize=False, to='garageApp.garageapp')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('profile_pic_url_string', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=255)),
                ('email_verified', models.BooleanField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicle_info', serialize=False, to='garageApp.garageapp')),
                ('type', models.CharField(max_length=100)),
                ('manufacture', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('model', models.CharField(choices=[('Rolley', 'Rolley'), ('Rolley Plus', 'Rolley Plus'), ('Icon', 'Icon')], max_length=20)),
                ('color', models.CharField(choices=[('Blue', 'Blue'), ('White', 'White'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Cyan', 'Cyan'), ('Red', 'Red'), ('Purple', 'Purple'), ('Black', 'Black'), ('Green', 'Green'), ('Neon Green', 'Neon Green'), ('Neon Pink', 'Neon Pink'), ('Neon Yellow', 'Neon Yellow'), ('Neon Red', 'Neon Red'), ('Neon Orange', 'Neon Orange'), ('Neon Purple', 'Neon Purple'), ('Carbon Fiber Black', 'Carbon Fiber Black')], max_length=20)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('length', models.IntegerField()),
                ('top_speed', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('power', models.IntegerField()),
                ('sn', models.CharField(max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('ecu', models.CharField(max_length=100)),
                ('gsm', models.CharField(max_length=100)),
                ('gps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('garage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vehicle_status', serialize=False, to='garageApp.garageapp')),
                ('battery_percentage', models.IntegerField()),
                ('power_on', models.BooleanField()),
                ('sharing_on', models.BooleanField()),
                ('alarm_on', models.BooleanField()),
                ('last_sync', models.TimeField(default=datetime.time(0, 0))),
                ('is_occupied', models.BooleanField()),
                ('odo_meter', models.IntegerField()),
                ('trip_meter', models.IntegerField()),
                ('gear_mode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicles', to='garageApp.garageapp')),
            ],
        ),
    ]
