# Generated by Django 4.2.2 on 2023-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garageapp',
            name='particle_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garageapp',
            name='particle_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garageapp',
            name='particle_serial',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
