# Generated by Django 4.2.2 on 2023-07-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0002_garageapp_particle_id_garageapp_particle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedvehicledata',
            name='idleTimeOption',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
