# Generated by Django 4.2.2 on 2023-07-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0003_sharedvehicledata_idletimeoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedvehicledata',
            old_name='idleTimeOption',
            new_name='idle_time_option',
        ),
    ]
