# Generated by Django 4.2.2 on 2023-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0004_rename_idletimeoption_sharedvehicledata_idle_time_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garageapp',
            options={'verbose_name_plural': 'Garage'},
        ),
        migrations.AlterModelOptions(
            name='sharedvehicledata',
            options={'verbose_name_plural': 'Shared Vehicle Data'},
        ),
        migrations.AlterModelOptions(
            name='sharedvehicleownerdata',
            options={'verbose_name_plural': 'Shared Vehicle Owner Data'},
        ),
        migrations.AlterModelOptions(
            name='vehicleinfo',
            options={'verbose_name_plural': 'Vehicle Info'},
        ),
        migrations.AlterModelOptions(
            name='vehiclestatus',
            options={'verbose_name_plural': 'Vehicle Status'},
        ),
        migrations.AddField(
            model_name='sharedvehicleownerdata',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedvehicleownerdata',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedvehicleownerdata',
            name='weight_in_kg',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
