# Generated by Django 4.2.2 on 2023-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0005_alter_garageapp_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageapp',
            name='vehicle_id',
            field=models.CharField(error_messages={'unique': 'This vehicle has already been registered.'}, max_length=100, primary_key=True, serialize=False),
        ),
    ]
