# Generated by Django 4.2.2 on 2023-07-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0006_alter_garageapp_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garageapp',
            name='particle_id',
            field=models.CharField(error_messages={'unique': 'Vehicle with this particle ID already exists'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='garageapp',
            name='particle_serial',
            field=models.CharField(error_messages={'unique': 'Vehicle with this particle serial already exists'}, max_length=100, unique=True),
        ),
    ]
